import html
import json
import os
import re
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Sequence
from urllib.parse import quote, urlsplit
from xml.etree import ElementTree as ET

from .database import Database
from .normalize import strip_control_characters


SOURCE_COLORS = {
    "openai-news": "#10a37f",
    "openai-developers": "#2563eb",
    "claude-blog": "#d97757",
    "anthropic-news": "#7c3aed",
}

PAGE_ARTICLE_LIMIT = 500
LATEST_JSON_ARTICLE_LIMIT = 500
FEED_ARTICLE_LIMIT = 100
DIGEST_ARTICLE_LIMIT = 100

SUPPORTED_LANGUAGES = ("en", "zh-CN")
_HEALTH_CODES = frozenset(("healthy", "never_synced", "stale", "error", "degraded"))

_TRANSLATIONS = {
    "en": {
        "eyebrow": "Deterministic feed reader",
        "subtitle": (
            "Fixed programs fetch, deduplicate, and organize; normal operation "
            "uses 0 LLM tokens."
        ),
        "counter": (
            "Articles: {total} · Unread: {unread} · "
            "Showing latest: {returned} (limit: {limit})"
        ),
        "health_healthy": "Healthy",
        "health_never_synced": "Never synced",
        "health_stale": "Stale",
        "health_error": "Error",
        "health_degraded": "Degraded",
        "source_counts": "Articles: {articles} / Unread: {unread}",
        "pending": " · Pending: {pending}",
        "language_label": "Language",
        "search_placeholder": "Search titles, summaries, or categories",
        "all_sources": "All sources",
        "all_statuses": "All reading states",
        "unread_only": "Unread only",
        "unread_badge": "Unread",
        "empty": "No articles match these filters.",
        "generated_footer": "Generated at {generated} · Prepared by the cloud update pipeline",
        "digest_title": "Aaron Reader Unread Digest",
        "program_generated": "Generated by a fixed program; LLM tokens: 0.",
        "digest_empty": "There are no unread articles.",
        "digest_summary": (
            "Showing the latest {returned} of {total} unread articles "
            "(limit: {limit})."
        ),
        "feed_description": "Deterministic AI lab subscriptions",
        "packet_instruction": (
            "Send this object to an LLM only when necessary; fixed programs have "
            "already fetched, deduplicated, and filtered the articles."
        ),
        "machine_translation": "Publisher metadata translation",
        "metadata_basis": "Publisher metadata only",
        "full_text_basis": "Extracted full text",
        "ai_generated": "AI generated · {basis} · {language} · {generated}",
        "ai_truncated": "Input was truncated",
    },
    "zh-CN": {
        "eyebrow": "确定性订阅阅读器",
        "subtitle": "固定程序抓取、去重与整理；正常运行消耗 0 LLM token。",
        "counter": "总计 {total} 篇 · {unread} 未读 · 页面显示最近 {returned} 篇（上限 {limit}）",
        "health_healthy": "正常",
        "health_never_synced": "未同步",
        "health_stale": "过期",
        "health_error": "异常",
        "health_degraded": "降级",
        "source_counts": "{articles} 篇 / {unread} 未读",
        "pending": " · {pending} 待补全",
        "language_label": "语言",
        "search_placeholder": "搜索标题、简介或类别",
        "all_sources": "全部来源",
        "all_statuses": "全部状态",
        "unread_only": "只看未读",
        "unread_badge": "未读",
        "empty": "没有符合条件的文章。",
        "generated_footer": "生成于 {generated} · 由云端更新流水线生成",
        "digest_title": "Aaron Reader 未读摘要",
        "program_generated": "固定程序生成；LLM token：0。",
        "digest_empty": "目前没有未读文章。",
        "digest_summary": "列出最近 {returned} / {total} 篇未读文章（上限 {limit}）。",
        "feed_description": "确定性的 AI 实验室订阅",
        "packet_instruction": "仅在确有需要时把本对象交给 LLM；抓取、去重和筛选已由固定程序完成。",
        "machine_translation": "发布方元数据翻译",
        "metadata_basis": "仅发布方元数据",
        "full_text_basis": "已提取文章全文",
        "ai_generated": "AI 生成 · {basis} · {language} · {generated}",
        "ai_truncated": "输入已截断",
    },
}
_MARKDOWN_PUNCTUATION = re.compile(r"([!\"#$%&'()*+,\-./:;<=>?@\[\\\]^_`{|}~])")


def render_outputs(
    database: Database,
    output_dir: Path,
    *,
    language: str = "en",
) -> None:
    resolved_language = _normalize_language(language)
    output_dir.mkdir(parents=True, exist_ok=True)
    recent_limit = max(PAGE_ARTICLE_LIMIT, LATEST_JSON_ARTICLE_LIMIT, FEED_ARTICLE_LIMIT)
    recent_articles = database.list_articles(limit=recent_limit)
    artifact_map = database.latest_ai_artifacts(
        [int(article["id"]) for article in recent_articles]
    )
    recent_articles = [
        dict(
            article,
            ai_artifacts=_translation_ai_artifacts(
                artifact_map.get(int(article["id"]), [])
            ),
        )
        for article in recent_articles
    ]
    page_articles = recent_articles[:PAGE_ARTICLE_LIMIT]
    latest_articles = recent_articles[:LATEST_JSON_ARTICLE_LIMIT]
    feed_articles = recent_articles[:FEED_ARTICLE_LIMIT]
    digest_articles = database.list_articles(
        limit=DIGEST_ARTICLE_LIMIT,
        unread_only=True,
    )
    statuses = database.source_statuses()
    counts = database.counts()
    _atomic_write(
        output_dir / "index.html",
        render_html(
            page_articles,
            statuses,
            counts=counts,
            article_limit=PAGE_ARTICLE_LIMIT,
            language=resolved_language,
        ),
    )
    _atomic_write(
        output_dir / "latest.json",
        render_json(
            latest_articles,
            statuses,
            counts=counts,
            article_limit=LATEST_JSON_ARTICLE_LIMIT,
            language=resolved_language,
        ),
    )
    _atomic_write(
        output_dir / "feed.xml",
        render_feed(feed_articles, language=resolved_language),
    )
    _atomic_write(
        output_dir / "digest.md",
        render_digest(
            digest_articles,
            total_count=counts["unread"],
            article_limit=DIGEST_ARTICLE_LIMIT,
            language=resolved_language,
        ),
    )


def render_index(
    database: Database,
    *,
    language: str = "en",
) -> str:
    """Render a fresh index without mutating any generated artifact."""

    resolved_language = _normalize_language(language)
    articles = database.list_articles(limit=PAGE_ARTICLE_LIMIT)
    artifact_map = database.latest_ai_artifacts(
        [int(article["id"]) for article in articles]
    )
    articles = [
        dict(
            article,
            ai_artifacts=_translation_ai_artifacts(
                artifact_map.get(int(article["id"]), [])
            ),
        )
        for article in articles
    ]
    return render_html(
        articles,
        database.source_statuses(),
        counts=database.counts(),
        article_limit=PAGE_ARTICLE_LIMIT,
        language=resolved_language,
    )


def render_html(
    articles: Sequence[Dict[str, object]],
    statuses: Sequence[Dict[str, object]],
    *,
    counts: Optional[Dict[str, int]] = None,
    article_limit: Optional[int] = None,
    language: str = "en",
) -> str:
    resolved_language = _normalize_language(language)
    translations = _TRANSLATIONS[resolved_language]
    resolved_counts = _resolve_counts(articles, statuses, counts)
    total_count = resolved_counts["total"]
    unread_count = resolved_counts["unread"]
    page_limit = max(0, int(article_limit if article_limit is not None else len(articles)))
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    status_cards = []
    for source in statuses:
        health = _source_health(source)
        pending_count = int(source.get("pending_count") or 0)
        source_article_count = int(source.get("article_count") or 0)
        source_unread_count = int(source.get("unread_count") or 0)
        pending_markup = (
            '<span data-i18n-template="pending" data-pending="%d">%s</span>'
            % (
                pending_count,
                html.escape(
                    _format_translation(
                        resolved_language,
                        "pending",
                        pending=pending_count,
                    )
                ),
            )
            if pending_count
            else ""
        )
        status_cards.append(
            """
            <article class="source-card">
              <div><span class="dot" style="--dot:%s"></span><strong>%s</strong></div>
              <span class="health %s"><span data-i18n="health_%s">%s</span> · <span data-i18n-template="source_counts" data-articles="%d" data-unread="%d">%s</span>%s</span>
            </article>
            """
            % (
                SOURCE_COLORS.get(str(source["slug"]), "#64748b"),
                html.escape(_output_text(source["name"])),
                health,
                health,
                html.escape(translations["health_%s" % health]),
                source_article_count,
                source_unread_count,
                html.escape(
                    _format_translation(
                        resolved_language,
                        "source_counts",
                        articles=source_article_count,
                        unread=source_unread_count,
                    )
                ),
                pending_markup,
            )
        )
    cards = []
    for article in articles:
        source_slug = _output_text(article["source_slug"])
        published = _output_text(
            article.get("published_at") or article.get("discovered_at") or ""
        )[:10]
        unread = not article.get("read_at")
        ai_artifact_markup, ai_search_text = _render_ai_artifacts(
            article.get("ai_artifacts"), resolved_language
        )
        searchable = " ".join(
            _output_text(article.get(key) or "")
            for key in ("title", "summary", "category", "source_name")
        ) + " " + ai_search_text
        searchable = searchable.lower()
        title = html.escape(_output_text(article["title"]))
        article_url = _safe_http_url(article.get("canonical_url"))
        title_markup = (
            '<a href="%s" target="_blank" rel="noopener noreferrer">%s</a>'
            % (html.escape(article_url, quote=True), title)
            if article_url
            else title
        )
        cards.append(
            """
            <article class="article-card%s" data-article-id="%d" data-source="%s" data-unread="%s" data-search="%s">
              <div class="meta">
                <span class="source" style="--source:%s">%s</span>
                <time>%s</time>%s%s
              </div>
              <h2>%s</h2>
              %s
              %s
            </article>
            """
            % (
                " unread" if unread else "",
                int(article["id"]),
                html.escape(source_slug, quote=True),
                "1" if unread else "0",
                html.escape(searchable, quote=True),
                SOURCE_COLORS.get(source_slug, "#64748b"),
                html.escape(_output_text(article["source_name"])),
                html.escape(published),
                (
                    '<span class="category">%s</span>'
                    % html.escape(_output_text(article["category"]))
                    if article.get("category")
                    else ""
                ),
                (
                    '<span class="unread-label" data-i18n="unread_badge">%s</span>'
                    % html.escape(translations["unread_badge"])
                    if unread
                    else ""
                ),
                title_markup,
                (
                    "<p>%s</p>" % html.escape(_output_text(article["summary"]))
                    if article.get("summary")
                    else ""
                ),
                ai_artifact_markup,
            )
        )
    counter_text = _format_translation(
        resolved_language,
        "counter",
        total=total_count,
        unread=unread_count,
        returned=len(articles),
        limit=page_limit,
    )
    footer_text = _format_translation(
        resolved_language,
        "generated_footer",
        generated=generated,
    )
    translations_json = json.dumps(
        _TRANSLATIONS,
        ensure_ascii=False,
        separators=(",", ":"),
    ).replace("<", "\\u003c").replace("&", "\\u0026")
    return """<!doctype html>
<html lang="%s">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="color-scheme" content="light dark">
  <title>Aaron Reader</title>
  <style>
    :root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033;background:#f5f6f8;line-height:1.55}
    *{box-sizing:border-box}body{margin:0}.shell{width:min(1080px,calc(100%% - 32px));margin:0 auto;padding:54px 0 80px}
    header.hero{display:flex;gap:24px;align-items:flex-end;justify-content:space-between;margin-bottom:28px}.eyebrow{letter-spacing:.13em;text-transform:uppercase;font-size:12px;color:#64748b;font-weight:750}
    h1{font-size:clamp(34px,6vw,62px);line-height:1;margin:.15em 0}.subtitle{margin:0;color:#64748b}.hero-actions{display:flex;align-items:flex-end;gap:10px;flex-direction:column}.counter{font-size:14px;color:#475569;background:white;border:1px solid #e2e8f0;padding:10px 14px;border-radius:999px;white-space:nowrap}.language-picker{display:flex;align-items:center;gap:8px;color:#64748b;font-size:13px}.language-picker select{font:inherit;border:1px solid #dbe1e8;border-radius:9px;background:#fff;color:inherit;padding:7px 9px}
    .sources{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:24px 0}.source-card{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:13px;display:flex;gap:8px;flex-direction:column}.dot{display:inline-block;width:9px;height:9px;border-radius:50%%;background:var(--dot);margin-right:7px}.health{font-size:12px;color:#64748b}.health.error{color:#b42318}.health.degraded,.health.stale{color:#b45309}.health.never_synced{color:#475569}
    .toolbar{position:sticky;top:10px;z-index:3;display:flex;gap:10px;padding:10px;background:rgba(245,246,248,.92);backdrop-filter:blur(14px);border:1px solid rgba(226,232,240,.9);border-radius:16px;margin-bottom:18px}.toolbar input,.toolbar select{font:inherit;border:1px solid #dbe1e8;border-radius:10px;background:#fff;color:inherit;padding:10px 12px}.toolbar input{flex:1;min-width:120px}.empty{display:none;text-align:center;color:#64748b;padding:48px}
    .list{display:grid;gap:12px}.article-card{position:relative;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:20px 22px;box-shadow:0 8px 24px rgba(15,23,42,.035)}.article-card.unread{border-left:4px solid var(--accent,#111827)}.article-card[hidden]{display:none}.meta{display:flex;align-items:center;gap:10px;flex-wrap:wrap;font-size:12px;color:#64748b}.source{color:var(--source);font-weight:750}.category,.unread-label{background:#f1f5f9;border-radius:999px;padding:2px 8px}.unread-label{background:#e0f2fe;color:#0369a1}.article-card h2{font-size:20px;line-height:1.35;margin:9px 0 5px}.article-card h2 a{color:inherit;text-decoration:none}.article-card h2 a:hover{text-decoration:underline}.article-card p{color:#536174;margin:7px 0 0;max-width:82ch}.ai-artifact{margin-top:14px;padding:14px 16px;border:1px solid #dbeafe;border-radius:12px;background:#f8fbff}.ai-label{font-size:12px;color:#475569}.ai-output{white-space:pre-line}.ai-points{margin:8px 0 0;padding-left:20px;color:#536174}.translated-title{font-size:17px;margin:9px 0 4px}.ai-warning{color:#b45309}
    footer{text-align:center;color:#94a3b8;font-size:12px;margin-top:34px}
    @media(max-width:780px){.shell{padding-top:28px}.sources{grid-template-columns:1fr 1fr}header.hero{align-items:flex-start;flex-direction:column}.hero-actions{align-items:flex-start}.toolbar{flex-wrap:wrap}.toolbar input{flex-basis:100%%}}
    @media(prefers-color-scheme:dark){:root{color:#e5e7eb;background:#0b0f17}.subtitle,.article-card p,.health,.meta,.ai-label,.ai-points{color:#94a3b8}.counter,.source-card,.article-card,.toolbar{background:#121824;border-color:#273244}.toolbar{background:rgba(11,15,23,.9)}.toolbar input,.toolbar select,.language-picker select{background:#0d1420;border-color:#334155;color:#e5e7eb}.category{background:#273244}.unread-label{background:#0c4a6e;color:#bae6fd}.ai-artifact{background:#0e1726;border-color:#1e3a5f}}
  </style>
</head>
<body><main class="shell">
  <header class="hero"><div><div class="eyebrow" data-i18n="eyebrow">%s</div><h1>Aaron Reader</h1><p class="subtitle" data-i18n="subtitle">%s</p></div><div class="hero-actions"><div class="counter" data-i18n-template="counter" data-total="%d" data-unread="%d" data-returned="%d" data-limit="%d">%s</div><label class="language-picker"><span data-i18n="language_label">%s</span><select id="language"><option value="en"%s>English</option><option value="zh-CN"%s>简体中文</option></select></label></div></header>
  <section class="sources">%s</section>
  <section class="toolbar"><input id="search" type="search" data-i18n-placeholder="search_placeholder" placeholder="%s"><select id="source"><option value="" data-i18n="all_sources">%s</option>%s</select><select id="read"><option value="" data-i18n="all_statuses">%s</option><option value="1" data-i18n="unread_only">%s</option></select></section>
  <section class="list" id="list">%s</section><p class="empty" id="empty" data-i18n="empty">%s</p>
  <footer data-i18n-template="generated_footer" data-generated="%s">%s</footer>
</main><script id="aaron-reader-translations" type="application/json">%s</script><script>
const translations=JSON.parse(document.querySelector('#aaron-reader-translations').textContent),supportedLanguages=['en','zh-CN'],languageSelector=document.querySelector('#language');
function interpolate(template,element){return template.replace(/\\{(\\w+)\\}/g,(_,key)=>element.dataset[key]??'')}
function applyLanguage(nextLanguage,persist=false){if(!supportedLanguages.includes(nextLanguage))nextLanguage='en';const messages=translations[nextLanguage];document.documentElement.lang=nextLanguage;document.querySelectorAll('[data-i18n]').forEach(element=>{const message=messages[element.dataset.i18n];if(message!==undefined)element.textContent=message});document.querySelectorAll('[data-i18n-template]').forEach(element=>{const message=messages[element.dataset.i18nTemplate];if(message!==undefined)element.textContent=interpolate(message,element)});document.querySelectorAll('[data-i18n-placeholder]').forEach(element=>{const message=messages[element.dataset.i18nPlaceholder];if(message!==undefined)element.placeholder=message});languageSelector.value=nextLanguage;if(persist){try{localStorage.setItem('aaron-reader-language',nextLanguage)}catch(error){}}}
let initialLanguage=document.documentElement.lang;try{const savedLanguage=localStorage.getItem('aaron-reader-language');if(supportedLanguages.includes(savedLanguage))initialLanguage=savedLanguage}catch(error){}
languageSelector.addEventListener('change',()=>applyLanguage(languageSelector.value,true));applyLanguage(initialLanguage);
const cards=[...document.querySelectorAll('.article-card')],search=document.querySelector('#search'),source=document.querySelector('#source'),read=document.querySelector('#read'),empty=document.querySelector('#empty');
function filter(){const q=search.value.trim().toLowerCase(),s=source.value,u=read.value;let shown=0;for(const card of cards){const ok=(!q||card.dataset.search.includes(q))&&(!s||card.dataset.source===s)&&(!u||card.dataset.unread===u);card.hidden=!ok;if(ok)shown++}empty.style.display=shown?'none':'block'}
[search,source,read].forEach(x=>x.addEventListener('input',filter));filter();
</script></body></html>""" % (
        html.escape(resolved_language, quote=True),
        html.escape(translations["eyebrow"]),
        html.escape(translations["subtitle"]),
        total_count,
        unread_count,
        len(articles),
        page_limit,
        html.escape(counter_text),
        html.escape(translations["language_label"]),
        ' selected="selected"' if resolved_language == "en" else "",
        ' selected="selected"' if resolved_language == "zh-CN" else "",
        "".join(status_cards),
        html.escape(translations["search_placeholder"], quote=True),
        html.escape(translations["all_sources"]),
        "".join(
            '<option value="%s">%s</option>'
            % (
                html.escape(_output_text(source["slug"]), quote=True),
                html.escape(_output_text(source["name"])),
            )
            for source in statuses
        ),
        html.escape(translations["all_statuses"]),
        html.escape(translations["unread_only"]),
        "".join(cards),
        html.escape(translations["empty"]),
        html.escape(generated, quote=True),
        html.escape(footer_text),
        translations_json,
    )


def render_json(
    articles: Sequence[Dict[str, object]],
    statuses: Sequence[Dict[str, object]],
    *,
    counts: Optional[Dict[str, int]] = None,
    article_limit: Optional[int] = None,
    language: str = "en",
) -> str:
    resolved_language = _normalize_language(language)
    resolved_counts = _resolve_counts(articles, statuses, counts)
    returned_count = len(articles)
    result_limit = max(
        0,
        int(article_limit if article_limit is not None else returned_count),
    )
    omitted_count = max(0, resolved_counts["total"] - returned_count)
    cached_ai_artifact_count = sum(
        len(_translation_ai_artifacts(article.get("ai_artifacts")))
        for article in articles
    )
    payload = {
        "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "language": resolved_language,
        "supported_languages": list(SUPPORTED_LANGUAGES),
        "llm_tokens_used": 0,
        "render_llm_tokens_used": 0,
        "cached_ai_artifact_count": cached_ai_artifact_count,
        "counts": resolved_counts,
        "articles_page": {
            "order": "newest_first",
            "returned_count": returned_count,
            "limit": result_limit,
            "omitted_count": omitted_count,
            "truncated": omitted_count > 0,
        },
        "sources": [
            {
                "slug": _output_text(source["slug"]),
                "name": _output_text(source["name"]),
                "health": _source_health(source),
                "last_success_at": _output_text(source.get("last_success_at")) or None,
                "last_error": _output_text(source.get("last_error")) or None,
                "article_count": int(source.get("article_count") or 0),
                "unread_count": int(source.get("unread_count") or 0),
                "pending_count": int(source.get("pending_count") or 0),
            }
            for source in statuses
        ],
        "articles": [_public_article(article) for article in articles],
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def render_digest(
    articles: Sequence[Dict[str, object]],
    *,
    total_count: Optional[int] = None,
    article_limit: Optional[int] = None,
    language: str = "en",
) -> str:
    resolved_language = _normalize_language(language)
    translations = _TRANSLATIONS[resolved_language]
    resolved_total = max(len(articles), int(total_count or 0))
    resolved_limit = max(
        0,
        int(article_limit if article_limit is not None else len(articles)),
    )
    lines = [
        "# %s" % translations["digest_title"],
        "",
        translations["program_generated"],
        "",
    ]
    if not articles:
        lines.append(translations["digest_empty"])
        return "\n".join(lines) + "\n"
    lines.extend(
        [
            _format_translation(
                resolved_language,
                "digest_summary",
                returned=len(articles),
                total=resolved_total,
                limit=resolved_limit,
            ),
            "",
        ]
    )
    for article in articles:
        date = _escape_markdown(
            _output_text(article.get("published_at") or article.get("discovered_at") or "")[:10]
        )
        title = _escape_markdown(article["title"])
        url = _safe_http_url(article.get("canonical_url"))
        title_markup = "[%s](<%s>)" % (title, url) if url else title
        lines.append(
            "- %s — %s · %s"
            % (title_markup, _escape_markdown(article["source_name"]), date)
        )
        if article.get("summary"):
            lines.append("  %s" % _escape_markdown(article["summary"]))
    return "\n".join(lines) + "\n"


def render_feed(
    articles: Sequence[Dict[str, object]],
    *,
    language: str = "en",
) -> str:
    resolved_language = _normalize_language(language)
    rss = ET.Element("rss", {"version": "2.0"})
    channel = ET.SubElement(rss, "channel")
    ET.SubElement(channel, "title").text = "Aaron Reader"
    ET.SubElement(channel, "description").text = _TRANSLATIONS[resolved_language][
        "feed_description"
    ]
    ET.SubElement(channel, "language").text = resolved_language
    ET.SubElement(channel, "link").text = (
        "https://aaron-reader.aaron-he-zhu.workers.dev/"
    )
    ET.SubElement(channel, "lastBuildDate").text = datetime.now(timezone.utc).strftime(
        "%a, %d %b %Y %H:%M:%S +0000"
    )
    for article in articles:
        item = ET.SubElement(channel, "item")
        ET.SubElement(item, "title").text = _output_text(article["title"])
        safe_url = _safe_http_url(article.get("canonical_url"))
        if safe_url:
            ET.SubElement(item, "link").text = safe_url
        guid = safe_url or "urn:aaron-reader:%s" % quote(
            _output_text(article.get("id") or "unknown"), safe=""
        )
        ET.SubElement(item, "guid").text = guid
        ET.SubElement(item, "description").text = _output_text(article.get("summary") or "")
        ET.SubElement(item, "category").text = _output_text(article.get("source_name") or "")
        if article.get("published_at"):
            try:
                parsed = datetime.fromisoformat(
                    _output_text(article["published_at"]).replace("Z", "+00:00")
                )
                ET.SubElement(item, "pubDate").text = parsed.strftime("%a, %d %b %Y %H:%M:%S +0000")
            except ValueError:
                pass
    return '<?xml version="1.0" encoding="utf-8"?>\n' + ET.tostring(
        rss, encoding="unicode", short_empty_elements=True
    ) + "\n"


def build_llm_packet(
    articles: Sequence[Dict[str, object]],
    max_chars: int = 6000,
    *,
    language: str = "en",
) -> Dict[str, object]:
    if not isinstance(max_chars, int) or isinstance(max_chars, bool) or max_chars <= 0:
        raise ValueError("max_chars must be a positive integer")
    resolved_language = _normalize_language(language)

    total_article_count = len(articles)
    selected: List[Dict[str, object]] = []
    truncated_summary_count = 0
    empty_packet = _finalize_packet(
        [],
        max_chars,
        total_article_count=total_article_count,
        truncated_summary_count=0,
        language=resolved_language,
    )
    if int(empty_packet["character_count"]) > max_chars:
        raise ValueError("max_chars is too small for packet metadata")

    for article in articles:
        item = _public_article(article)
        original_summary = str(item.get("summary") or "")
        summary = original_summary[:600]
        compact = {
            "id": item["id"],
            "source": item["source"],
            "published_at": item["published_at"],
            "title": item["title"],
            "summary": summary,
            "url": item["url"],
        }
        candidate_was_truncated = len(summary) < len(original_summary)
        trial = _finalize_packet(
            selected + [compact],
            max_chars,
            total_article_count=total_article_count,
            truncated_summary_count=truncated_summary_count + int(candidate_was_truncated),
            language=resolved_language,
        )
        if int(trial["character_count"]) > max_chars and summary:
            best_summary: Optional[str] = None
            lower = 0
            upper = len(summary)
            while lower <= upper:
                midpoint = (lower + upper) // 2
                candidate_summary = summary[:midpoint].rstrip()
                compact["summary"] = candidate_summary
                candidate_was_truncated = candidate_summary != original_summary
                trial = _finalize_packet(
                    selected + [compact],
                    max_chars,
                    total_article_count=total_article_count,
                    truncated_summary_count=(
                        truncated_summary_count + int(candidate_was_truncated)
                    ),
                    language=resolved_language,
                )
                if int(trial["character_count"]) <= max_chars:
                    best_summary = candidate_summary
                    lower = midpoint + 1
                else:
                    upper = midpoint - 1
            if best_summary is not None:
                compact["summary"] = best_summary
                candidate_was_truncated = best_summary != original_summary
                trial = _finalize_packet(
                    selected + [compact],
                    max_chars,
                    total_article_count=total_article_count,
                    truncated_summary_count=(
                        truncated_summary_count + int(candidate_was_truncated)
                    ),
                    language=resolved_language,
                )
        if int(trial["character_count"]) > max_chars:
            break
        selected.append(compact)
        truncated_summary_count += int(candidate_was_truncated)
    packet = _finalize_packet(
        selected,
        max_chars,
        total_article_count=total_article_count,
        truncated_summary_count=truncated_summary_count,
        language=resolved_language,
    )
    if int(packet["character_count"]) > max_chars:
        raise RuntimeError("final packet exceeds its character budget")
    return packet


def _finalize_packet(
    articles: Sequence[Dict[str, object]],
    max_chars: int,
    *,
    total_article_count: int,
    truncated_summary_count: int,
    language: str,
) -> Dict[str, object]:
    omitted_article_count = max(0, total_article_count - len(articles))
    packet: Dict[str, object] = {
        "language": language,
        "supported_languages": list(SUPPORTED_LANGUAGES),
        "instruction_hint": _TRANSLATIONS[language]["packet_instruction"],
        "input_article_count": total_article_count,
        "article_count": len(articles),
        "omitted_article_count": omitted_article_count,
        "truncated_summary_count": truncated_summary_count,
        "truncated": bool(omitted_article_count or truncated_summary_count),
        "character_budget": max_chars,
        "character_count": 0,
        "utf8_bytes": 0,
        "approx_tokens": 0,
        "articles": list(articles),
    }
    for _ in range(64):
        serialized = _pretty_packet_json(packet)
        character_count = len(serialized)
        utf8_bytes = len(serialized.encode("utf-8"))
        approx_tokens = (utf8_bytes + 3) // 4
        values = (
            int(packet["character_count"]),
            int(packet["utf8_bytes"]),
            int(packet["approx_tokens"]),
        )
        updated = (character_count, utf8_bytes, approx_tokens)
        packet["character_count"] = character_count
        packet["utf8_bytes"] = utf8_bytes
        packet["approx_tokens"] = approx_tokens
        if values == updated:
            break
    else:
        raise RuntimeError("packet size metadata did not converge")

    serialized = _pretty_packet_json(packet)
    if int(packet["character_count"]) != len(serialized):
        raise RuntimeError("packet character_count is not self-consistent")
    if int(packet["utf8_bytes"]) != len(serialized.encode("utf-8")):
        raise RuntimeError("packet utf8_bytes is not self-consistent")
    return packet


def _translation_ai_artifacts(value: object) -> List[Dict[str, object]]:
    """Expose only per-article translations while accepting legacy caches."""

    if not isinstance(value, list):
        return []
    return [
        item
        for item in value
        if isinstance(item, dict)
        and _output_text(item.get("task_type") or item.get("task"))
        == "translation"
    ]


def _public_article(article: Dict[str, object]) -> Dict[str, object]:
    result = {
        "id": article["id"],
        "source": _output_text(article["source_slug"]),
        "source_name": _output_text(article["source_name"]),
        "title": _output_text(article["title"]),
        "summary": _output_text(article.get("summary") or ""),
        "category": _output_text(article.get("category") or ""),
        "published_at": _output_text(article.get("published_at")) or None,
        "url": _safe_http_url(article.get("canonical_url")),
        "unread": not bool(article.get("read_at")),
        "starred": bool(article.get("starred_at")),
    }
    result["ai_artifacts"] = [
        _public_ai_artifact(item)
        for item in _translation_ai_artifacts(article.get("ai_artifacts"))
    ]
    return result


def _public_ai_artifact(artifact: Dict[str, object]) -> Dict[str, object]:
    try:
        output = json.loads(_output_text(artifact.get("output_json") or "{}"))
    except (TypeError, ValueError, json.JSONDecodeError):
        output = {}
    if not isinstance(output, dict):
        output = {}
    return {
        "id": int(artifact.get("id") or 0),
        "task": _output_text(
            artifact.get("task_type") or artifact.get("task") or ""
        ),
        "input_scope": _output_text(artifact.get("input_scope") or ""),
        "target_language": _output_text(artifact.get("target_language") or ""),
        "generated_at": _output_text(artifact.get("created_at") or "") or None,
        "input_truncated": bool(artifact.get("input_truncated")),
        "output": output,
    }


def _render_ai_artifacts(
    value: object, language: str
) -> tuple:
    if not isinstance(value, list):
        return "", ""
    translations = _TRANSLATIONS[language]
    markup: List[str] = []
    search_parts: List[str] = []
    for raw_artifact in _translation_ai_artifacts(value):
        artifact = _public_ai_artifact(raw_artifact)
        task = str(artifact["task"])
        scope = str(artifact["input_scope"])
        basis_key = "full_text_basis" if scope == "full_text" else "metadata_basis"
        label_key = "machine_translation"
        output = artifact["output"]
        if not isinstance(output, dict):
            output = {}
        body = ""
        translated_title = _output_text(output.get("title") or "")
        translated_summary = _output_text(output.get("publisher_summary") or "")
        search_parts.extend((translated_title, translated_summary))
        if translated_title:
            body += '<h3 class="translated-title">%s</h3>' % html.escape(
                translated_title
            )
        if translated_summary:
            body += '<p class="ai-output">%s</p>' % html.escape(
                translated_summary
            )
        if not body:
            continue
        generated = str(artifact.get("generated_at") or "")[:10]
        truncated = (
            ' · <span class="ai-warning" data-i18n="ai_truncated">%s</span>'
            % html.escape(translations["ai_truncated"])
            if artifact.get("input_truncated")
            else ""
        )
        markup.append(
            """
            <section class="ai-artifact" data-ai-task="%s" data-ai-language="%s">
              <div class="ai-label"><strong data-i18n="%s">%s</strong> · <span data-i18n="%s">%s</span> · <span>%s</span> · <time>%s</time>%s</div>
              %s
            </section>
            """
            % (
                html.escape(task, quote=True),
                html.escape(str(artifact["target_language"]), quote=True),
                label_key,
                html.escape(translations[label_key]),
                basis_key,
                html.escape(translations[basis_key]),
                html.escape(str(artifact["target_language"])),
                html.escape(generated),
                truncated,
                body,
            )
        )
    return "".join(markup), " ".join(search_parts)


def _pretty_packet_json(packet: Dict[str, object]) -> str:
    """Match the CLI's pretty JSON plus the newline emitted by ``print``."""

    return json.dumps(packet, ensure_ascii=False, indent=2) + "\n"


def _normalize_language(language: str) -> str:
    if not isinstance(language, str):
        raise ValueError("language must be 'en' or 'zh-CN'")
    normalized = language.strip().replace("_", "-").lower()
    if normalized == "en" or normalized.startswith("en-"):
        return "en"
    if normalized == "zh" or normalized.startswith("zh-"):
        return "zh-CN"
    raise ValueError("unsupported language %r; expected 'en' or 'zh-CN'" % language)


def _format_translation(language: str, key: str, **values: object) -> str:
    return _TRANSLATIONS[language][key].format(**values)


def _output_text(value: object) -> str:
    if value is None:
        return ""
    text = strip_control_characters(str(value))
    return re.sub(r"\s+", " ", text).strip()


def _safe_http_url(value: object) -> str:
    if value is None:
        return ""
    raw = str(value).strip()
    sanitized = strip_control_characters(raw, preserve_text_whitespace=False)
    if sanitized != raw:
        return ""
    try:
        parts = urlsplit(sanitized)
        if parts.scheme.lower() not in ("http", "https") or not parts.hostname:
            return ""
        if parts.username or parts.password:
            return ""
    except (TypeError, ValueError):
        return ""
    return quote(sanitized, safe=":/?#[]@!$&'()*+,;=%")


def _escape_markdown(value: object) -> str:
    text = _output_text(value)
    return _MARKDOWN_PUNCTUATION.sub(lambda match: "\\" + match.group(1), text)


def _source_health(source: Dict[str, object]) -> str:
    configured = _output_text(source.get("health")).lower()
    if configured in _HEALTH_CODES:
        return configured
    if source.get("last_error"):
        return "error"
    if not source.get("last_success_at"):
        return "never_synced"
    return "healthy"


def _resolve_counts(
    articles: Sequence[Dict[str, object]],
    statuses: Sequence[Dict[str, object]],
    counts: Optional[Dict[str, int]],
) -> Dict[str, int]:
    if counts is not None:
        return {
            "total": max(0, int(counts.get("total") or 0)),
            "unread": max(0, int(counts.get("unread") or 0)),
            "starred": max(0, int(counts.get("starred") or 0)),
        }
    has_aggregates = bool(statuses) and all("article_count" in source for source in statuses)
    total = (
        sum(int(source.get("article_count") or 0) for source in statuses)
        if has_aggregates
        else len(articles)
    )
    unread = (
        sum(int(source.get("unread_count") or 0) for source in statuses)
        if has_aggregates
        else sum(1 for article in articles if not article.get("read_at"))
    )
    return {
        "total": max(0, total),
        "unread": max(0, unread),
        "starred": sum(1 for article in articles if article.get("starred_at")),
    }


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=path.name + ".", dir=str(path.parent))
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    except Exception:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise
