"use client";

import { useEffect, useMemo, useState } from "react";

import {
  artifactPayload,
  artifactSearchText,
  findArtifact,
  type AIArtifact,
} from "./ai-artifacts";
import { findLatestReport, reportPayload, type AIReport } from "./ai-reports";
import {
  CODEX_WORKSPACE_PATH,
  articleCodexLink,
  backfillCodexLink,
  reportCodexLink,
  type ReportPeriod,
} from "./codex-actions";

type Language = "en" | "zh-CN";

type Article = {
  id: number;
  source: string;
  source_name: string;
  title: string;
  summary: string | null;
  category: string | null;
  published_at: string | null;
  url: string;
  ai_artifacts: AIArtifact[];
};

type Source = {
  slug: string;
  name: string;
  health: string;
  last_success_at: string | null;
  article_count: number;
};

type Snapshot = {
  generated_at: string;
  language: string;
  supported_languages: string[];
  llm_tokens_used: number;
  render_llm_tokens_used: number;
  cached_ai_artifact_count: number;
  ai_reports?: AIReport[];
  sources: Source[];
  articles: Article[];
};

const copy = {
  en: {
    eyebrow: "Independent signal desk",
    titleA: "The work behind",
    titleB: "the AI frontier.",
    intro:
      "OpenAI, Anthropic, and Claude updates in one calm, deterministic feed. Collection, parsing, and publishing use fixed programs—not an LLM.",
    updated: "Updated",
    articles: "articles",
    sources: "sources",
    zero: "LLM tokens for collection",
    search: "Search the archive",
    allSources: "All sources",
    showing: "Showing",
    of: "of",
    noResults: "No articles match this view.",
    clear: "Clear filters",
    read: "Read original",
    more: "Show more",
    system: "System",
    collection: "Collection",
    deterministic: "Fixed program · 10:00 & 22:00 San Francisco",
    enrichment: "AI enrichment",
    enrichmentValue: "Twice daily · GPT-5.6 Luna · Medium",
    language: "Language",
    sourceHealth: "Source health",
    healthy: "Healthy",
    degraded: "Degraded",
    error: "Error",
    never_synced: "Awaiting first sync",
    cached: "cached AI results",
    aiSummary: "AI summary",
    aiTranslation: "AI translation",
    generatedCached: "AI-generated · cached",
    metadataBasis: "Publisher metadata",
    fullTextBasis: "Extracted full text",
    generatedOn: "Generated",
    inputTruncated: "Input truncated",
    feed: "RSS feed",
    digest: "Markdown digest",
    actionKicker: "On-demand AI",
    actionTitle: "Brief it with Codex.",
    actionIntro:
      "Create a brief in the current interface language with your signed-in ChatGPT subscription. The website never sends a model request itself.",
    summarizeToday: "Summarize today in English",
    summarizeWeek: "Summarize this week in English",
    backfillThree: "Backfill 3 articles in Chinese",
    backfillHint: "Optional · bounded to three",
    coverage: "AI cache coverage",
    coverageSuffix: "articles enriched. Historical backfill runs only when you choose it.",
    codexReview:
      "Opens Codex with a prefilled prompt. Review the prompt, then press Send—the link does not submit or run anything automatically.",
    workspacePath: "Local Aaron Reader checkout",
    workspacePlaceholder: "/absolute/path/to/aaron-reader",
    workspaceHint: "Saved only in this browser. Leave blank to choose or clone the GitHub repository in Codex.",
    summarizeArticle: "Summarize in English",
    translateArticle: "Translate to Chinese",
    articleActions: "On-demand AI actions",
    aiTools: "AI tools",
    opensCodex: "Opens Codex; review the prompt before sending.",
    cachedShort: "Cached",
    reports: "AI briefs",
    dailyReport: "Daily brief",
    weeklyReport: "Weekly brief",
    reportTimezone: "San Francisco time",
    reportItems: "Source notes",
    noReports: "No daily or weekly AI brief has been published yet.",
    reportLimitations: "Scope note",
    policy:
      "AI summaries and translations are generated by local scheduled or on-demand Codex tasks using your signed-in ChatGPT subscription, cached, then published here. This site itself makes no model or API calls and needs no API key.",
    footer: "Built for signal, not engagement.",
  },
  "zh-CN": {
    eyebrow: "独立信号台",
    titleA: "读懂 AI 前沿",
    titleB: "背后的工作。",
    intro:
      "把 OpenAI、Anthropic 与 Claude 的更新汇集成一份安静、确定性的订阅。采集、解析和发布均由固定程序完成，不调用 LLM。",
    updated: "更新时间",
    articles: "篇文章",
    sources: "个来源",
    zero: "采集所用 LLM token",
    search: "搜索全部文章",
    allSources: "全部来源",
    showing: "当前显示",
    of: "共",
    noResults: "没有符合当前条件的文章。",
    clear: "清除筛选",
    read: "阅读原文",
    more: "显示更多",
    system: "系统",
    collection: "订阅采集",
    deterministic: "固定程序 · 旧金山时间 10:00、22:00",
    enrichment: "AI 增强",
    enrichmentValue: "每天两次 · GPT-5.6 Luna · Medium",
    language: "语言",
    sourceHealth: "来源状态",
    healthy: "正常",
    degraded: "降级",
    error: "错误",
    never_synced: "等待首次同步",
    cached: "个已缓存 AI 结果",
    aiSummary: "AI 摘要",
    aiTranslation: "AI 翻译",
    generatedCached: "AI 生成 · 已缓存",
    metadataBasis: "仅发布方元数据",
    fullTextBasis: "已提取文章全文",
    generatedOn: "生成于",
    inputTruncated: "输入已截断",
    feed: "RSS 订阅",
    digest: "Markdown 摘要",
    actionKicker: "按需 AI",
    actionTitle: "交给 Codex 生成简报。",
    actionIntro: "使用已登录的 ChatGPT 订阅，按当前界面语言生成范围明确的简报；网页本身不会发送模型请求。",
    summarizeToday: "总结今天",
    summarizeWeek: "总结本周",
    backfillThree: "补齐接下来 3 篇中文内容",
    backfillHint: "可选 · 每次最多三篇",
    coverage: "AI 缓存覆盖",
    coverageSuffix: "篇文章已有 AI 内容；历史回填仅在你主动选择时运行。",
    codexReview: "链接会打开 Codex 并预填指令；请先检查，再按“发送”。它不会自动提交或执行任务。",
    workspacePath: "Aaron Reader 本地目录",
    workspacePlaceholder: "/绝对路径/aaron-reader",
    workspaceHint: "仅保存在当前浏览器；留空时可在 Codex 中选择或克隆 GitHub 仓库。",
    summarizeArticle: "生成中文摘要",
    translateArticle: "翻译为中文",
    articleActions: "按需 AI 操作",
    aiTools: "AI 工具",
    opensCodex: "将在 Codex 中打开；发送前请检查预填指令。",
    cachedShort: "已缓存",
    reports: "AI 简报",
    dailyReport: "今日简报",
    weeklyReport: "本周简报",
    reportTimezone: "旧金山时间",
    reportItems: "本期文章",
    noReports: "目前还没有已发布的日报或周报。",
    reportLimitations: "范围说明",
    policy: "AI 摘要和翻译由本地定时或按需 Codex 任务使用已登录的 ChatGPT 订阅生成，缓存后再发布到这里。网站本身不调用模型或 API，也不需要 API Key。",
    footer: "为信号而建，而非为互动量而建。",
  },
} as const;

const sourceColor: Record<string, string> = {
  "openai-news": "#0d8a6a",
  "openai-developers": "#2463d4",
  "claude-blog": "#c25f3c",
  "anthropic-news": "#7047b8",
};

function formatDate(value: string | null, language: Language, long = false) {
  if (!value) return "—";
  const date = new Date(value);
  return new Intl.DateTimeFormat(language, long
    ? { year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "Asia/Singapore", timeZoneName: "short" }
    : { year: "numeric", month: "short", day: "numeric", timeZone: "Asia/Singapore" }
  ).format(date);
}

function formatReportWindow(report: AIReport, language: Language) {
  const start = report.period_start;
  const end = report.period_end;
  if (!start || !end) return report.local_date || "—";

  const dateFormatter = new Intl.DateTimeFormat(language, {
    year: "numeric",
    month: "short",
    day: "numeric",
    timeZone: "America/Los_Angeles",
  });
  const cutoffFormatter = new Intl.DateTimeFormat(language, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    timeZone: "America/Los_Angeles",
    timeZoneName: "short",
  });
  return `${dateFormatter.format(new Date(start))} → ${cutoffFormatter.format(new Date(end))}`;
}

export function Reader({ snapshot }: { snapshot: Snapshot }) {
  const [language, setLanguage] = useState<Language>("en");
  const [query, setQuery] = useState("");
  const [source, setSource] = useState("");
  const [visible, setVisible] = useState(36);
  const [workspacePath, setWorkspacePath] = useState(CODEX_WORKSPACE_PATH);
  const t = copy[language];
  const reportPeriods: ReportPeriod[] = ["daily", "weekly"];

  useEffect(() => {
    const stored = window.localStorage.getItem("aaron-reader-language");
    const frame = window.requestAnimationFrame(() => {
      if (stored === "zh-CN" || stored === "en") setLanguage(stored);
    });
    return () => window.cancelAnimationFrame(frame);
  }, []);

  useEffect(() => {
    const stored = window.localStorage.getItem("aaron-reader-workspace-path");
    if (stored) {
      const frame = window.requestAnimationFrame(() => setWorkspacePath(stored));
      return () => window.cancelAnimationFrame(frame);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    window.localStorage.setItem("aaron-reader-language", language);
  }, [language]);

  const filtered = useMemo(() => {
    const needle = query.trim().toLocaleLowerCase(language);
    return snapshot.articles.filter((article) => {
      if (source && article.source !== source) return false;
      if (!needle) return true;
      const artifact = findArtifact(article.ai_artifacts, "translation", language);
      const translated = artifactPayload(artifact);
      const haystack = [
        article.title,
        article.summary,
        article.category,
        article.source_name,
        translated.title,
        translated.publisherSummary,
        ...artifactSearchText(article.ai_artifacts),
      ].filter(Boolean).join(" ").toLocaleLowerCase(language);
      return haystack.includes(needle);
    });
  }, [language, query, snapshot.articles, source]);

  const articlesById = useMemo(
    () => new Map(snapshot.articles.map((article) => [article.id, article])),
    [snapshot.articles],
  );
  const enrichedArticleCount = useMemo(
    () => snapshot.articles.filter((article) => article.ai_artifacts.length > 0).length,
    [snapshot.articles],
  );
  const publishedReports = reportPeriods.flatMap((period) => {
    const report = findLatestReport(snapshot.ai_reports, period, language);
    return report ? [{ period, report, payload: reportPayload(report) }] : [];
  });

  const chooseLanguage = (next: Language) => {
    setLanguage(next);
  };

  const reset = () => {
    setQuery("");
    setSource("");
  };

  return (
    <main>
      <header className="masthead">
        <a className="wordmark" href="#top" aria-label="Aaron Reader home">
          <span className="wordmark-mark" aria-hidden="true">A</span>
          <span>Aaron Reader</span>
        </a>
        <nav className="topnav" aria-label={t.language}>
          <a href="/reader/feed.xml">{t.feed}</a>
          <a href="/reader/digest.md">{t.digest}</a>
          <span className="language-switch" role="group" aria-label={t.language}>
            <button className={language === "en" ? "active" : ""} onClick={() => chooseLanguage("en")}>EN</button>
            <span aria-hidden="true">/</span>
            <button className={language === "zh-CN" ? "active" : ""} onClick={() => chooseLanguage("zh-CN")}>简</button>
          </span>
        </nav>
      </header>

      <div className="page" id="top">
        <section className="hero" aria-labelledby="page-title">
          <div>
            <p className="eyebrow"><span className="live-dot" />{t.eyebrow}</p>
            <h1 id="page-title"><span>{t.titleA}</span> {t.titleB}</h1>
          </div>
          <div className="hero-copy">
            <p>{t.intro}</p>
            <p className="timestamp">{t.updated} · {formatDate(snapshot.generated_at, language, true)}</p>
          </div>
        </section>

        <section className="metrics" aria-label="Reader metrics">
          <div><strong>{snapshot.articles.length}</strong><span>{t.articles}</span></div>
          <div><strong>{snapshot.sources.length}</strong><span>{t.sources}</span></div>
          <div><strong>{snapshot.render_llm_tokens_used}</strong><span>{t.zero}</span></div>
        </section>

        <section className="codex-center" aria-labelledby="codex-center-title">
          <div className="codex-center-copy">
            <p className="panel-kicker">{t.actionKicker}</p>
            <h2 id="codex-center-title">{t.actionTitle}</h2>
            <p className="codex-center-intro">{t.actionIntro}</p>
            <p className="ai-coverage">
              <span>{t.coverage}</span>
              <strong>{enrichedArticleCount}/{snapshot.articles.length}</strong>
              {t.coverageSuffix}
            </p>
          </div>
          <div className="codex-center-controls">
            <label className="codex-workspace-field">
              <span>{t.workspacePath}</span>
              <input
                type="text"
                value={workspacePath}
                onChange={(event) => {
                  const value = event.target.value;
                  setWorkspacePath(value);
                  window.localStorage.setItem("aaron-reader-workspace-path", value);
                }}
                placeholder={t.workspacePlaceholder}
                autoComplete="off"
                spellCheck={false}
              />
              <small>{t.workspaceHint}</small>
            </label>
            <div className="codex-global-actions" role="group" aria-label={t.actionKicker}>
              <a className="codex-action codex-action-primary" href={reportCodexLink("daily", language, workspacePath)} aria-describedby="codex-review-note">
                <span>{t.summarizeToday}</span><span aria-hidden="true">↗</span>
              </a>
              <a className="codex-action" href={reportCodexLink("weekly", language, workspacePath)} aria-describedby="codex-review-note">
                <span>{t.summarizeWeek}</span><span aria-hidden="true">↗</span>
              </a>
              <a className="codex-action codex-action-backfill" href={backfillCodexLink(workspacePath)} aria-describedby="codex-review-note">
                <span>{t.backfillThree}<small>{t.backfillHint}</small></span><span aria-hidden="true">↗</span>
              </a>
            </div>
            <p className="codex-review-note" id="codex-review-note"><span aria-hidden="true">◇</span>{t.codexReview}</p>
          </div>
        </section>

        <section className="workspace">
          <div className="stream">
            <div className="filters">
              <label className="search-field">
                <span aria-hidden="true">⌕</span>
                <input
                  type="search"
                  value={query}
                  onChange={(event) => {
                    setQuery(event.target.value);
                    setVisible(36);
                  }}
                  placeholder={t.search}
                  aria-label={t.search}
                />
              </label>
              <select value={source} onChange={(event) => {
                setSource(event.target.value);
                setVisible(36);
              }} aria-label={t.allSources}>
                <option value="">{t.allSources}</option>
                {snapshot.sources.map((item) => <option key={item.slug} value={item.slug}>{item.name}</option>)}
              </select>
            </div>

            {publishedReports.length > 0 && (
              <section className="report-section" aria-labelledby="report-section-title">
                <div className="report-section-heading">
                  <h2 className="panel-kicker" id="report-section-title">{t.reports}</h2>
                  <span>{t.reportTimezone}</span>
                </div>
                <div className="report-grid">
                  {publishedReports.map(({ period, report, payload }) => (
                    <article
                      className="report-card"
                      key={`${period}-${report.id || report.generated_at || report.period_end}`}
                      lang={report.target_language || report.output?.language || language}
                    >
                      <div className="report-card-meta">
                        <strong>{period === "daily" ? t.dailyReport : t.weeklyReport}</strong>
                        <span className="report-ai-status"><i />{t.generatedCached}</span>
                      </div>
                      <p className="report-window">{formatReportWindow(report, language)}</p>
                      {payload.headline && <h3>{payload.headline}</h3>}
                      {payload.overview && <p className="report-overview">{payload.overview}</p>}
                      {payload.items.length > 0 && (
                        <details className="report-items">
                          <summary>
                            <span>{t.reportItems}</span>
                            <strong>{payload.items.length}</strong>
                            <span className="report-disclosure" aria-hidden="true">+</span>
                          </summary>
                          <ol>
                            {payload.items.map((item) => {
                              const article = articlesById.get(item.articleId);
                              return (
                                <li key={`${report.id || period}-${item.articleId}`}>
                                  {article ? (
                                    <a href={article.url} target="_blank" rel="noopener noreferrer">{item.title}</a>
                                  ) : <strong>{item.title}</strong>}
                                  <p>{item.summary}</p>
                                </li>
                              );
                            })}
                          </ol>
                          {payload.limitations && (
                            <p className="report-limitations"><strong>{t.reportLimitations}:</strong> {payload.limitations}</p>
                          )}
                        </details>
                      )}
                      <div className="report-footer">
                        {report.model && <span>{report.model}</span>}
                        {report.generated_at && (
                          <time dateTime={report.generated_at}>{t.generatedOn} {formatDate(report.generated_at, language)}</time>
                        )}
                        {report.input_truncated && <span className="ai-warning">{t.inputTruncated}</span>}
                      </div>
                    </article>
                  ))}
                </div>
              </section>
            )}

            <div className="stream-heading">
              <p>{t.showing} <strong>{Math.min(filtered.length, visible)}</strong> {t.of} {filtered.length}</p>
              {(query || source) && <button onClick={reset}>{t.clear}</button>}
            </div>

            <div className="article-list">
              {filtered.slice(0, visible).map((article, index) => {
                const translationArtifact = findArtifact(article.ai_artifacts, "translation", language);
                const translation = artifactPayload(translationArtifact);
                const chineseTranslationArtifact = findArtifact(article.ai_artifacts, "translation", "zh-CN");
                const chineseTranslation = artifactPayload(chineseTranslationArtifact);
                const summaryArtifact = findArtifact(article.ai_artifacts, "summary", language);
                const aiSummary = artifactPayload(summaryArtifact);
                const title = translation.title || article.title;
                const publisherSummary = translation.publisherSummary || article.summary;
                const hasTranslation = Boolean(translation.title || translation.publisherSummary);
                const hasChineseTranslation = Boolean(
                  chineseTranslation.title || chineseTranslation.publisherSummary,
                );
                const hasAISummary = Boolean(aiSummary.summary || aiSummary.keyPoints.length);
                const cachedToolCount = Number(hasAISummary) + Number(hasChineseTranslation);
                return (
                  <article className="article" key={article.id} style={{ "--source-color": sourceColor[article.source] || "#171717" } as React.CSSProperties}>
                    <span className="article-index" aria-hidden="true">{String(index + 1).padStart(2, "0")}</span>
                    <div className="article-body">
                      <div className="article-meta">
                        <span className="source-name"><i />{article.source_name}</span>
                        <time dateTime={article.published_at || undefined}>{formatDate(article.published_at, language)}</time>
                        {article.category && <span>{article.category}</span>}
                      </div>
                      <h2><a href={article.url} target="_blank" rel="noopener noreferrer">{title}</a></h2>
                      {hasTranslation && (
                        <div className="ai-translation-note" aria-label={t.aiTranslation}>
                          <strong>{t.aiTranslation}</strong>
                          <span className="ai-state"><i />{t.generatedCached}</span>
                          {translationArtifact?.generated_at && (
                            <time dateTime={translationArtifact.generated_at}>
                              {t.generatedOn} {formatDate(translationArtifact.generated_at, language)}
                            </time>
                          )}
                        </div>
                      )}
                      {publisherSummary && <p>{publisherSummary}</p>}
                      {hasAISummary && (
                        <section className="ai-summary-card" aria-label={t.aiSummary}>
                          <div className="ai-summary-heading">
                            <strong>{t.aiSummary}</strong>
                            <span className="ai-state"><i />{t.generatedCached}</span>
                          </div>
                          {aiSummary.summary && <p>{aiSummary.summary}</p>}
                          {aiSummary.keyPoints.length > 0 && (
                            <ul>
                              {aiSummary.keyPoints.map((point, pointIndex) => (
                                <li key={`${summaryArtifact?.id || article.id}-${pointIndex}`}>{point}</li>
                              ))}
                            </ul>
                          )}
                          <div className="ai-summary-meta">
                            <span>{summaryArtifact?.input_scope === "full_text" ? t.fullTextBasis : t.metadataBasis}</span>
                            {summaryArtifact?.generated_at && (
                              <time dateTime={summaryArtifact.generated_at}>
                                {t.generatedOn} {formatDate(summaryArtifact.generated_at, language)}
                              </time>
                            )}
                            {summaryArtifact?.input_truncated && <span className="ai-warning">{t.inputTruncated}</span>}
                          </div>
                        </section>
                      )}
                      <div className="article-links">
                        <a className="read-link" href={article.url} target="_blank" rel="noopener noreferrer">{t.read}<span aria-hidden="true">↗</span></a>
                        <details className="article-ai-tools">
                          <summary>
                            <span>{t.aiTools}</span>
                            {cachedToolCount > 0 && <small>{cachedToolCount} {t.cachedShort}</small>}
                            <span className="article-tools-disclosure" aria-hidden="true">+</span>
                          </summary>
                          <div className="article-ai-actions" role="group" aria-label={t.articleActions}>
                            <div>
                              <a
                                className="article-ai-action"
                                href={articleCodexLink(article.id, "summary", language, workspacePath)}
                                aria-label={`${t.summarizeArticle}: ${article.title}`}
                              >
                                <span>{t.summarizeArticle}</span>
                                {hasAISummary && <small>✓ {t.cachedShort}</small>}
                                <span aria-hidden="true">↗</span>
                              </a>
                              <a
                                className="article-ai-action"
                                href={articleCodexLink(article.id, "translation", "zh-CN", workspacePath)}
                                aria-label={`${t.translateArticle}: ${article.title}`}
                              >
                                <span>{t.translateArticle}</span>
                                {hasChineseTranslation && <small>✓ {t.cachedShort}</small>}
                                <span aria-hidden="true">↗</span>
                              </a>
                            </div>
                            <p><span aria-hidden="true">◇</span>{t.opensCodex}</p>
                          </div>
                        </details>
                      </div>
                    </div>
                  </article>
                );
              })}
            </div>

            {filtered.length === 0 && <div className="empty"><p>{t.noResults}</p><button onClick={reset}>{t.clear}</button></div>}
            {visible < filtered.length && <button className="show-more" onClick={() => setVisible((count) => count + 36)}>{t.more} <span>+{Math.min(36, filtered.length - visible)}</span></button>}
          </div>

          <aside className="system-panel">
            <p className="panel-kicker">{t.system}</p>
            <dl className="system-list">
              <div><dt>{t.collection}</dt><dd><span className="status-dot healthy" />{t.deterministic}</dd></div>
              <div><dt>{t.enrichment}</dt><dd>{t.enrichmentValue}</dd></div>
              <div><dt>{t.language}</dt><dd>English / 简体中文</dd></div>
            </dl>
            <p className="policy">{t.policy}</p>
            <div className="health-block">
              <p>{t.sourceHealth}</p>
              {snapshot.sources.map((item) => (
                <div className="health-row" key={item.slug}>
                  <span>{item.name}</span>
                  <span className={`health-value ${item.health}`}><i />{t[item.health as keyof typeof t] || item.health}</span>
                </div>
              ))}
            </div>
            <p className="cache-note">{snapshot.cached_ai_artifact_count} {t.cached}</p>
          </aside>
        </section>
      </div>

      <footer><span>Aaron Reader · 2026</span><span>{t.footer}</span></footer>
    </main>
  );
}
